KEYS = [
    {'id': 1, 'type': 'function', 'name1': 'ESC', 'name2': ''},
    {'id': 2, 'type': 'function', 'name1': 'F1', 'name2': ''},
    {'id': 3, 'type': 'function', 'name1': 'F2', 'name2': ''},
    {'id': 4, 'type': 'function', 'name1': 'F3', 'name2': ''},
    {'id': 5, 'type': 'function', 'name1': 'F4', 'name2': ''},
    {'id': 6, 'type': 'function', 'name1': 'F5', 'name2': ''},
    {'id': 7, 'type': 'function', 'name1': 'F6', 'name2': ''},
    {'id': 8, 'type': 'function', 'name1': 'F7', 'name2': ''},
    {'id': 9, 'type': 'function', 'name1': 'F8', 'name2': ''},
    {'id': 10, 'type': 'function', 'name1': 'F9', 'name2': ''},
    {'id': 11, 'type': 'function', 'name1': 'F10', 'name2': ''},
    {'id': 12, 'type': 'function', 'name1': 'F11', 'name2': ''},
    {'id': 13, 'type': 'function', 'name1': 'F12', 'name2': ''},
    {'id': 14, 'type': 'function', 'name1': 'Print Screen', 'name2': ''},
    {'id': 15, 'type': 'function', 'name1': 'Scroll Lock', 'name2': ''},
    {'id': 16, 'type': 'function', 'name1': 'Pause Break', 'name2': ''},
    {'id': 17, 'type': 'normal', 'name1': '`', 'name2': '~'},
    {'id': 18, 'type': 'normal', 'name1': '1', 'name2': '!'},
    {'id': 19, 'type': 'normal', 'name1': '2', 'name2': '@'},
    {'id': 20, 'type': 'normal', 'name1': '3', 'name2': '#'},
    {'id': 21, 'type': 'normal', 'name1': '4', 'name2': '$'},
    {'id': 22, 'type': 'normal', 'name1': '5', 'name2': '%'},
    {'id': 23, 'type': 'normal', 'name1': '6', 'name2': '^'},
    {'id': 24, 'type': 'normal', 'name1': '7', 'name2': '&'},
    {'id': 25, 'type': 'normal', 'name1': '8', 'name2': '*'},
    {'id': 26, 'type': 'normal', 'name1': '9', 'name2': '('},
    {'id': 27, 'type': 'normal', 'name1': '0', 'name2': ')'},
    {'id': 28, 'type': 'normal', 'name1': '-', 'name2': '_'},
    {'id': 29, 'type': 'normal', 'name1': '=', 'name2': '+'},
    {'id': 30, 'type': 'function', 'name1': 'Backspace', 'name2': ''},
    {'id': 31, 'type': 'function', 'name1': 'Insert', 'name2': ''},
    {'id': 32, 'type': 'function', 'name1': 'Home', 'name2': ''},
    {'id': 33, 'type': 'function', 'name1': 'Page Up', 'name2': ''},
    {'id': 34, 'type': 'function', 'name1': 'Num Lock', 'name2': ''},
    {'id': 35, 'type': 'normal', 'name1': '/', 'name2': ''},
    {'id': 36, 'type': 'normal', 'name1': '*', 'name2': ''},
    {'id': 37, 'type': 'normal', 'name1': '-', 'name2': ''},
    {'id': 38, 'type': 'function', 'name1': 'Tab', 'name2': ''},
    {'id': 39, 'type': 'normal', 'name1': 'Q', 'name2': ''},
    {'id': 40, 'type': 'normal', 'name1': 'W', 'name2': 'Up'},
    {'id': 41, 'type': 'normal', 'name1': 'E', 'name2': ''},
    {'id': 42, 'type': 'normal', 'name1': 'R', 'name2': ''},
    {'id': 43, 'type': 'normal', 'name1': 'T', 'name2': ''},
    {'id': 44, 'type': 'normal', 'name1': 'Y', 'name2': ''},
    {'id': 45, 'type': 'normal', 'name1': 'U', 'name2': ''},
    {'id': 46, 'type': 'normal', 'name1': 'I', 'name2': ''},
    {'id': 47, 'type': 'normal', 'name1': 'O', 'name2': ''},
    {'id': 48, 'type': 'normal', 'name1': 'P', 'name2': ''},
    {'id': 49, 'type': 'normal', 'name1': '[', 'name2': '{'},
    {'id': 50, 'type': 'normal', 'name1': ']', 'name2': '}'},
    {'id': 51, 'type': 'normal', 'name1': '\\', 'name2': '|'},
    {'id': 52, 'type': 'function', 'name1': 'Delete', 'name2': ''},
    {'id': 53, 'type': 'function', 'name1': 'End', 'name2': ''},
    {'id': 54, 'type': 'function', 'name1': 'Page Down', 'name2': ''},
    {'id': 55, 'type': 'normal', 'name1': '7', 'name2': 'Home'},
    {'id': 56, 'type': 'normal', 'name1': '8', 'name2': 'Up'},
    {'id': 57, 'type': 'normal', 'name1': '9', 'name2': 'Page Up'},
    {'id': 58, 'type': 'normal', 'name1': '+', 'name2': ''},
    {'id': 59, 'type': 'function', 'name1': 'Caps Lock', 'name2': ''},
    {'id': 60, 'type': 'function', 'name1': 'A', 'name2': 'Left'},
    {'id': 61, 'type': 'function', 'name1': 'S', 'name2': 'Down'},
    {'id': 62, 'type': 'function', 'name1': 'D', 'name2': 'Right'},
    {'id': 63, 'type': 'normal', 'name1': 'F', 'name2': ''},
    {'id': 64, 'type': 'normal', 'name1': 'G', 'name2': ''},
    {'id': 65, 'type': 'normal', 'name1': 'H', 'name2': ''},
    {'id': 66, 'type': 'normal', 'name1': 'J', 'name2': ''},
    {'id': 67, 'type': 'normal', 'name1': 'K', 'name2': ''},
    {'id': 68, 'type': 'normal', 'name1': 'L', 'name2': ''},
    {'id': 69, 'type': 'normal', 'name1': ';', 'name2': ':'},
    {'id': 70, 'type': 'normal', 'name1': "'", 'name2': '"'},
    {'id': 71, 'type': 'function', 'name1': 'Enter', 'name2': ''},
    {'id': 72, 'type': 'normal', 'name1': '4', 'name2': 'Left'},
    {'id': 73, 'type': 'normal', 'name1': '5', 'name2': ''},
    {'id': 74, 'type': 'normal', 'name1': '6', 'name2': 'Right'},
    {'id': 75, 'type': 'function', 'name1': 'Left-Shift', 'name2': ''},
    {'id': 76, 'type': 'normal', 'name1': 'Z', 'name2': ''},
    {'id': 77, 'type': 'normal', 'name1': 'X', 'name2': ''},
    {'id': 78, 'type': 'normal', 'name1': 'C', 'name2': ''},
    {'id': 79, 'type': 'normal', 'name1': 'V', 'name2': ''},
    {'id': 80, 'type': 'normal', 'name1': 'B', 'name2': ''},
    {'id': 81, 'type': 'normal', 'name1': 'N', 'name2': ''},
    {'id': 82, 'type': 'normal', 'name1': 'M', 'name2': ''},
    {'id': 83, 'type': 'normal', 'name1': ',', 'name2': '<'},
    {'id': 84, 'type': 'normal', 'name1': '.', 'name2': '>'},
    {'id': 85, 'type': 'normal', 'name1': '/', 'name2': '?'},
    {'id': 86, 'type': 'function', 'name1': 'Right-Shift', 'name2': ''},
    {'id': 87, 'type': 'normal', 'name1': 'Up', 'name2': ''},
    {'id': 88, 'type': 'normal', 'name1': '1', 'name2': 'End'},
    {'id': 89, 'type': 'normal', 'name1': '2', 'name2': 'Down'},
    {'id': 90, 'type': 'normal', 'name1': '3', 'name2': 'Page Down'},
    {'id': 91, 'type': 'function', 'name1': 'Enter', 'name2': ''},
    {'id': 92, 'type': 'function', 'name1': 'Left-Control', 'name2': ''},
    {'id': 93, 'type': 'function', 'name1': 'Left-Windows', 'name2': ''},
    {'id': 94, 'type': 'function', 'name1': 'Left-Alt', 'name2': ''},
    {'id': 95, 'type': 'normal', 'name1': 'Space', 'name2': ''},
    {'id': 96, 'type': 'function', 'name1': 'Right-Alt', 'name2': ''},
    {'id': 97, 'type': 'function', 'name1': 'Fn', 'name2': ''},
    {'id': 98, 'type': 'function', 'name1': 'Right-Windows', 'name2': ''},
    {'id': 99, 'type': 'function', 'name1': 'Right-Control', 'name2': ''},
    {'id': 100, 'type': 'function', 'name1': 'Left', 'name2': ''},
    {'id': 101, 'type': 'function', 'name1': 'Down', 'name2': ''},
    {'id': 102, 'type': 'function', 'name1': 'Right', 'name2': ''},
    {'id': 103, 'type': 'normal', 'name1': '0', 'name2': 'Insert'},
    {'id': 104, 'type': 'normal', 'name1': '.', 'name2': 'Delete'}
]
